### ISSUE TITLE
target_folder - TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by jinnatar** [pycontribs/rtox#24]
~/python-cozify.git %> rtox -e py35 -e pep8
Traceback (most recent call last):
  File "/usr/local/bin/rtox", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/rtox/rtox.py", line 199, in cli
    target_folder = hashlib.sha1(repo).hexdigest()
TypeError: Unicode-objects must be encoded before hashing

 %> python3 -V
Python 3.5.2

 %> cat ~/.rtox.cfg 
[ssh]
user = root
hostname = vps
port = 22

Repo in question: https://github.com/Artanicus/python-cozify/tree/devel

**Comment by jinnatar** [comment]
Retried using Python2.7 and the same issue does not manifest. You may want to make it explicit in setup.py that Python3 is not supported, or rectify the situation.

**Comment by ssbarnea** [comment]
Any PRs would be appreciated, I will make a new release ASAP, if needed.
